platform :ios, '13'
use_frameworks!

def common
  pod 'Firebase/Core'
  #  pod 'dokstorSDK', :git => 'https://github.com/heliocor/dokstor-ios-sdk.git'
    pod 'dokstorSDK', :path => '../../dokstor-ios-sdk'
end

target 'DokstorSampleApp' do
  common
end

